# Generated by Django 4.2.7 on 2023-12-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_data_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
