# Generated by Django 4.2.7 on 2023-12-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_images', '0003_remove_product_image_data_base64_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_data_bytea',
        ),
    ]
